import type { z } from "zod";
import type { completionPolicySchema, specSchema } from "./schema";
export type Spec = z.infer<typeof specSchema>;
export type SpecCompletionPolicy = z.infer<typeof completionPolicySchema>;
export type { ArtifactKind, ArtifactReference, ArtifactSubject, ArtifactRevision, ValidationRecord, ApprovedSpecSnapshot } from "./artifacts";
export type { Requirement, AcceptanceCriterion, Requirements } from "./requirements";
export type { ProductDefinition, ProductOutcome, SuccessCriterion } from "./product";
export type { SystemArchitecture, ArchitectureDecision } from "./architecture";
export type { ProgramDesign, ProgramDesignDecision } from "./program-design";
export type { VerticalSlice, SlicePlan } from "./slices";
export type { SliceExecutionState, SliceExecutionStatus } from "./slice-state";
export type { Analysis, AnalysisFinding } from "./analysis";
export type { SpecMode, SpecLifecycle, LifecycleStatus } from "./lifecycle";
